# Generated by Django 4.0.4 on 2022-05-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Аксесуари', 'Аксесуари'), ('Антикваріат', 'Антикваріат'), ('Речі', 'Речі'), ('Декорації', 'Декорації'), ('Електроніка', 'Електроніка'), ('Коштовності', 'Коштовності'), ('Інше', 'Інше')], default='Other', max_length=11),
        ),
    ]
