# Generated by Django 4.0.4 on 2022-05-19 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_closed',
            field=models.DateField(default=datetime.date(2022, 5, 21)),
        ),
    ]
